version: '3'
services:
  express-rest-service:
    container_name: express-rest-service
    build:
      context: .
      dockerfile: Dockerfile
    # depends_on:
    #   - postgres
    environment:
      DATABASE_URL: postgres://postgres:password@postgres:5433/express-rest-service-db
      NODE_ENV: development
      PORT: 4000
    ports:
      - '4000:4000'
    # postgres:
    #   container_name: postgres
    #   image: postgres:13
    #   ports:
    #     - '5433:5433'
    #   volumes:
    #     - ./postgresdata:/var/lib/postgresql/data
    #   #   - ./src/migrations/dbinit.sql:/docker-entrypoint-initdb.d/dbinit.sql
    #   restart: always
    #   environment:
    #     POSTGRES_USER: postgres
    #     POSTGRES_PASSWORD: password
    #     POSTGRES_DB: express-rest-service-db
    # pgadmin:
    #   container_name: pgadmin
    #   image: dpage/pgadmin4:5.2
    #   restart: always
    #   environment:
    #     PGADMIN_DEFAULT_EMAIL: admin@linuxhint.com
    #     PGADMIN_DEFAULT_PASSWORD: password
    #     PGADMIN_LISTEN_PORT: 80
    #   ports:
    #     - '8080:80'
    #   volumes:
    #     - pgadmin-data:/var/lib/pgadmin
    #   depends_on:
    #     - postgres
  volumes:
  db-data:
  pgadmin-data:
