version: '3'
services:
  postgres:
    image: postgres:13.3
    ports:
      - '5433:5433'
    # environment:
    #   - POSTGRES_DB=hello_db
    #   - POSTGRES_USER=myuser
    env_file:
      - ./database/.env
    volumes:
      - .:/docker-entrypoint-initdb.d
    networks:
      - gateway
    deploy:
      restart_policy:
        condition: on-failure
  server:
    build: .
    depends_on:
      - postgres
    env_file:
      - .env
    ports:
      - '4000:4000'
    networks:
      - gateway
    deploy:
      restart_policy:
        condition: on-failure
    stdin_open: true
    tty: true
    volumes:
      - './:/usr/src/my-express-server-logs'
networks:
  gateway: {}
