version: '3'
services:
  express-rest-service:
    build: .
    depends_on:
      - postgres
    env_file:
      - .env
    ports:
      - '4000:4000'
  postgres:
    build: ./database
    ports:
      - '5433:5433'
    env_file:
      - ./database/.env
