version: '3'
services:
  server:
    build: .
    depends_on:
      - postgres
    env_file:
      - .env
    ports:
      - '4000:4000'
    networks:
      - gateway
    deploy:
      restart_policy:
        condition: on-failure
    stdin_open: true
    tty: true
    volumes:
      - './:/usr/src/my-express-server-logs'
  postgres:
    build: ./database
    ports:
      - '5433:5433'
    env_file:
      - ./database/.env
    networks:
      - gateway
    deploy:
      restart_policy:
        condition: on-failure
networks:
  gateway: {}
