version: '3'
services:
  db:
    image: postgres
    env_file:
      - .env
    ports:
      - ${DB_PORT}:${DB_PORT}
    networks:
      - my-network
    volumes:
      - ./pgdata:/var/lib/postgresql/data
      - ./src/database/init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
    deploy:
      restart_policy:
        condition: on-failure
  web:
    image: server-image
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    volumes:
      # - ./logs:/usr/app/logs
      - '../test dir:/usr/src/app/logs'
    networks:
      - my-network
    deploy:
      restart_policy:
        condition: on-failure
networks:
  my-network:
    driver: bridge
