version: '3'
services:
  db:
    image: postgres
    env_file:
      - .env
    ports:
      - ${DB_PORT}:${DB_PORT}
    volumes:
      - ./pgdata:/var/lib/postgresql/data
  web:
    image: server-image
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
